### ISSUE TITLE
/beskeder endpointet crasher, hvis der er flere sider

### ISSUE THREAD

**Issue by Asguho** [BetterLectio/BetterLectio-Flask-Backend#2]
Når man laver en request til f.eks. "https://better-lectio-flask-backend.vercel.app/beskeder?id=-30", crasher api'en, da lectio siden har flere sider.
![image](https://user-images.githubusercontent.com/78410939/206837747-cd134e22-d7dc-454d-b473-e3fa3e6a9484.png)
er det muligt, når denne fejl bliver fikset, at man crawler siden med alle beskeder

**Comment by jona799t** [comment]
Det er fikset nu
