### ISSUE TITLE
/check-cooke endpointet returnere altid false

### ISSUE THREAD

**Issue by Asguho** [BetterLectio/BetterLectio-Flask-Backend#3]
fejl for at reproducere
- kør dev brachen.
- åben http://127.0.0.1:5173/auth
- login
- gå fra forsiden tilbage til http://127.0.0.1:5173/auth
- se /check-cooke returnere:
![image](https://user-images.githubusercontent.com/78410939/206838040-5a60f85d-ee1d-4671-92dc-e8bb0af11a87.png)

cookien kan aldrig være noget at expire, da man har fået den fra mindre end 5 sekunder, og alle andre endpoints virker med cookien pånær /check-cooke, som altid returnere, at den ikke er valid.

**Comment by jona799t** [comment]
Det er fikset nu
